version: "3.8"

services:
  mysql:
    container_name: credit-db
    image: mysql:9.1.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=credit-db
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - performance-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 4G
    cpuset: "0-1"

  app:
    container_name: credit-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - performance-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 4G
    cpuset: "2-3"

networks:
  performance-test:
    name: performance-test
